import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.locator('body').click();
  await page.goto('https://staging.webuyanybike.com/');
  await page.getByRole('link', { name: 'Accept' }).click();
  await page.getByPlaceholder('Enter Your Reg').click();
  await page.getByPlaceholder('Enter Your Reg').click();
  await page.getByPlaceholder('Enter Your Reg').fill('ND18WYK');
  await page.getByPlaceholder('Enter Mileage').click();
  await page.getByPlaceholder('Enter Mileage').click();
  await page.getByPlaceholder('Enter Mileage').fill('1000');
  await page.getByRole('button', { name: 'Value My Bike' }).click();
  await page.getByRole('textbox', { name: 'Enter your name' }).click();
  await page.getByRole('textbox', { name: 'Enter your name' }).fill('soala');
  await page.getByRole('textbox', { name: 'Enter your email address' }).click();
  await page.getByRole('textbox', { name: 'Enter your email address' }).fill('');
  await page.getByRole('textbox', { name: 'Enter your email address' }).click();
  await page.getByRole('textbox', { name: 'Enter your email address' }).fill('soala@digitakumi.com');
  await page.getByRole('textbox', { name: 'Enter your mobile number' }).click();
  await page.getByRole('textbox', { name: 'Enter your mobile number' }).fill('07950779806');
  await page.getByLabel('By checking this box, I agree').check();
  await page.getByRole('button', { name: 'Get my bike valuation' }).click();
  await page.locator('select[name="serviceHistory"]').selectOption('Full History');
  await page.locator('[id="__next"] div').filter({ hasText: 'Please select how much' }).nth(3).click();
  await page.getByRole('button', { name: 'No' }).first().click();
  await page.getByRole('button', { name: 'No' }).nth(1).click();
  await page.getByRole('button', { name: 'No' }).nth(2).click();
  await page.locator('select[name="reasonForSelling"]').selectOption('I need to sell as I want another bike');
  await page.locator('select[name="bikeCondition"]').selectOption('4 - Good');
  await page.getByRole('button', { name: 'Yes' }).nth(3).click();
  await page.getByRole('button', { name: 'Get my bike valuation' }).click();
  await page.goto('https://staging.webuyanybike.com/get-quote/live-price/');
  await page.getByRole('button', { name: 'Wed, 7 Aug' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Confirm Bike Condition' }).click();
  await page.getByPlaceholder('Postcode...').click();
  await page.getByPlaceholder('Postcode...').press('CapsLock');
  await page.getByPlaceholder('Postcode...').fill('SE3 0RL');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('option', { name: '6 Montpelier Row, London SE3' }).click();
  await page.getByRole('button', { name: 'Save Address' }).click();
  await page.getByRole('button', { name: 'County...' }).click();
  await page.getByRole('option', { name: 'London', exact: true }).click();
  await page.getByRole('button', { name: 'Save Address' }).click();
  await page.locator('button[name="question_2"]').nth(1).click();
  await page.locator('button[name="question_3"]').first().click();
  await page.locator('button[name="question_6"]').nth(1).click();
  await page.locator('button[name="question_4"]').nth(1).click();
  await page.locator('button[name="question_47"]').first().click();
  await page.locator('button[name="question_57"]').nth(1).click();
  await page.locator('button[name="question_23"]').nth(1).click();
  await page.locator('button[name="question_24"]').first().click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('button[name="question_5"]').first().click();
  await page.locator('button[name="question_7"]').first().click();
  await page.locator('button[name="question_29"]').first().click();
  await page.locator('button[name="question_33"]').first().click();
  await page.locator('button[name="question_34"]').first().click();
  await page.locator('button[name="question_35"]').first().click();
  await page.locator('button[name="question_36"]').first().click();
  await page.locator('button[name="question_38"]').nth(1).click();
  await page.locator('button[name="question_39"]').first().click();
  await page.locator('button[name="question_44"]').first().click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('button[name="question_12"]').first().click();
  await page.locator('button[name="question_21"]').nth(1).click();
  await page.locator('button[name="question_48"]').nth(1).click();
  await page.locator('button[name="question_18"]').nth(1).click();
  await page.locator('button[name="question_31"]').first().click();
  await page.locator('button[name="question_20"]').first().click();
  await page.locator('button[name="question_37"]').first().click();
  await page.locator('button[name="question_25"]').first().click();
  await page.locator('button[name="question_40"]').first().click();
  await page.locator('button[name="question_41"]').first().click();
  await page.locator('button[name="question_42"]').first().click();
  await page.locator('button[name="question_30"]').first().click();
  await page.locator('button[name="question_27"]').first().click();
  await page.locator('button[name="question_28"]').first().click();
  await page.locator('button[name="question_16"]').nth(1).click();
  await page.getByRole('button', { name: 'Within 7 Days' }).click();
  await page.locator('button[name="question_19"]').nth(1).click();
  await page.locator('button[name="question_15"]').nth(1).click();
  await page.locator('button[name="question_17"]').nth(1).click();
  await page.locator('button[name="question_26"]').first().click();
  await page.locator('button[name="question_32"]').first().click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Yes' }).first().click();
  await page.getByRole('button', { name: 'No' }).nth(1).click();
  await page.getByRole('button', { name: 'No' }).nth(2).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Upload photos of my bike >>>' }).click();
  await page.getByRole('button', { name: 'Upload photos of my bike >>>' }).setInputFiles('Screenshot 2024-07-24 143519.png');
  await page.getByRole('button', { name: 'Upload images to webuyanybike' }).click();
  await page.getByRole('button', { name: 'Complete process' }).click();
});